# Generated by Django 4.2.7 on 2024-04-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_color_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='palitra',
            name='name',
            field=models.CharField(default='Палитра', max_length=255),
        ),
    ]
